### ISSUE TITLE
What pages / views are required for the app

### ISSUE THREAD

**Issue by davidgtonge** [backstopmedia/hubbub#10]
Here are some suggestions for starters:
1. Welcome
2. Main Dashboard - to view, filter and manage issues
3. Manage Repos - to add / remove repos to track
4. Edit Issue (should this be a modal dialog like trello?)

**Comment by afeld** [comment]
I think the managing of repos can be done on the Dashboard page, where you type in a search term and select a repo to add from a dropdown, and then the list of added repos has little X's next to them.

**Comment by davidgtonge** [comment]
Agree with that. What about editing / viewing individual issues. Should this be in a modal dialog? I think this could be good, as the user would see the results of any changes they make in the main dashboard view underneath

**Comment by afeld** [comment]
Works for me.

**Comment by davidgtonge** [comment]
I've done some more work on the wireframe. I'll finish off the modal in the morning (its after 11pm here). 
I'm more at home coding than wire-framing, but hopefully it will give us something to base the app around.

**Comment by davidgtonge** [comment]
I should be able to do quite a bit of work on the views tongiht.
