### ISSUE TITLE
Small logging view at bottom of screen

### ISSUE THREAD

**Issue by davidgtonge** [backstopmedia/hubbub#11]
As this is an example app, perhaps we could have a view which would be position at the bottom of the screen which would be an event log. We could listen to all events on all the views / models / collections and log it to this view. This could perhaps help people new to Backbone understand a bit more about when different events are fired. The view could be hidden by the user if needed.

**Comment by davidgtonge** [comment]
leave for now. Users can always log in the console
`app.board.issues.on("all",function(){console.log(arguments)});`

**Comment by afeld** [comment]
That's cool - maybe put that line in index.js, but commented out.
