### ISSUE TITLE
Do we need to render markdown content?

### ISSUE THREAD

**Issue by davidgtonge** [backstopmedia/hubbub#13]

**Comment by afeld** [comment]
Not if it's only the titles, but if we include descriptions, it looks like [markdown-js](https://github.com/evilstreak/markdown-js) and [marked](https://github.com/chjj/marked) are the parser-only options.  Haven't used either of them.

**Comment by davidgtonge** [comment]
I think we probably should include descriptions in the edit modal. Both libraries you referenced seem to have a fairly simple api - i.e. you pass in a string of markdown and a string of html is returned.

**Comment by caseywebdev** [comment]
I've added markdown-js, super easy to implement. `markdown.toHTML(issue.get('body'))`
