### ISSUE TITLE
Cache where we can

### ISSUE THREAD

**Issue by caseywebdev** [backstopmedia/hubbub#15]
GitHub's API request rate limit is only 60 per hour. In light of this, I think we need to cache vigorously. Fortunately, all of the CRUD operations are set up for `localStorage` so we can `save`/`fetch`/`destroy` for free (basically), synchronously. I've set up the app so far to `save` repos and the repo's issues when they are added to `app.board` in the side panel view. This way, when we load up the page again all the data is pulled locally. I think we should make all GitHub API requests explicit opt-ins from UI interactions (i.e. "click to fetch new data"). If we start doing automatic remote `fetch`es, however convenient it might be for certain parts of the app, we're going to hit that limit very quickly.

**Comment by afeld** [comment]
Done, right?

**Comment by caseywebdev** [comment]
Yup! Even though I just hit the rate limit lol
