### ISSUE TITLE
name for application

### ISSUE THREAD

**Issue by tbranyen** [backstopmedia/hubbub#2]
Lets try and figure this out :dancer:

**Comment by afeld** [comment]
someone brought up Kanban - good working title

**Comment by caseywebdev** [comment]
GitHug, the GitHub dashboard you'll love so much you want to hug it.

**Comment by davidgtonge** [comment]
Something short is good, I like the the github theme. Another one for the mix could be GitHubbub - as in a place to manage all the noise.

**Comment by troymott** [comment]
I reviewed their trademark policy and we need to not use git or hub in our app name.

**Comment by afeld** [comment]
We should rename the repo too - gets confusing (and caused a conflict in [hub](http://defunkt.io/hub/)) with the repo we're, ya know, writing about.

**Comment by caseywebdev** [comment]
I like hubbub :+1: short and sweet

**Comment by afeld** [comment]
According to @troymott, no "hub", bub.

**Comment by troymott** [comment]
I do like it as well, but I was looking here (https://help.github.com/articles/github-trademark-policy). I will go ahead and submit it to the link at the bottom of that page and see if we get any response by tomorrow morning.

**Comment by caseywebdev** [comment]
I don't think they can do anything about 'hubbub', it's a completely different word and hub is the first syllable rather than the second...

How bout `issuer`?

**Comment by troymott** [comment]
Okay, let's do it. It's also an actual word. I really like the name.

**Comment by caseywebdev** [comment]
done! time to move on from this =p

**Comment by afeld** [comment]
Everyone make sure to run `git remote set-url origin git@github.com:backstopmedia/hubbub.git`
