### ISSUE TITLE
Add close modals method on main view

### ISSUE THREAD

**Issue by davidgtonge** [backstopmedia/hubbub#26]
At the moment, clicking back in the browser leaves the modal open.

**Comment by tbranyen** [comment]
I'll try and tackle this.

**Comment by tbranyen** [comment]
Closed in 52dd6b3

**Comment by afeld** [comment]
Opening a modal should probably close all other modals, just for safety.

**Comment by tbranyen** [comment]
with the latest code I pushed, that is the case
