### ISSUE TITLE
Remove `app.User`

### ISSUE THREAD

**Issue by afeld** [backstopmedia/hubbub#36]
It's confusing with a mix of `app.User` objects and anonymous user objects under the issues and repos.  I think we should go all the way (with some relation plugin), or just take out this model.  The only place it's used

``` javascript
var user = new app.User({login: match[1]});
this.findReposFor(user);
```

can be refactored to

``` javascript
app.Repo.Collection.findByUsername(match[1]);
```

**Comment by caseywebdev** [comment]
Done
