### ISSUE TITLE
Welcome message disappeared?

### ISSUE THREAD

**Issue by afeld** [backstopmedia/hubbub#38]
Or did someone intentionally remove it?

**Comment by afeld** [comment]
My mistake - it's only if you stay in the same tab and don't close the browser (the `window.name` hack), which I think this is a bit confusing.  @caseywebdev suggested adding a "do not show again" checkbox, which makes it a bit more explicit.  We might store it as a cookie or in localStorage instead.

**Comment by caseywebdev** [comment]
``` js
'change .js-toggle-welcome': 'toggleWelcome'
...
toggleWelcome: function (ev) {
  app.board.set('showWelcome', $(ev.currentTarget).is(':checked')).save();
}
```

And just do a check for the flag in the view also, pretty easy :+1:

**Comment by caseywebdev** [comment]
Changed to an opt-out.
