### ISSUE TITLE
childViews?

### ISSUE THREAD

**Issue by afeld** [backstopmedia/hubbub#44]
Not to totally re-create a myriad of plugins, but what if we had an `addChildView()` method in our `app.View` class, and overrode the `remove()` method there to clean them up?  Or is this over-engineering for this app we want to show the basics?

**Comment by philfreo** [comment]
i wouldn't

**Comment by tbranyen** [comment]
i'd say time to include layoutmanager :-p

**Comment by afeld** [comment]
Cool - see #46
