### ISSUE TITLE
upgrade to Backbone 1.0.x

### ISSUE THREAD

**Issue by afeld** [backstopmedia/hubbub#52]
Work started in `backbone-1.0.0` branch - I'm seeing the same failure in the tests and the app itself, around `Board.Model#parse()`.

https://github.com/backstopmedia/hubbub/compare/complete...backbone-1.0.0

**Comment by afeld** [comment]
When this is ready, very easy to add to upgrade `boilerplate`:

``` bash
git checkout boilerplate
git cherry-pick 28846614719027f530a802f24dd56d159a116114
```

**Comment by afeld** [comment]
Also, I verified that the particular issue I'm seeing is from the Backbone 0.9.10->1.0.0 upgrade specifically, not the other upgrades.

**Comment by afeld** [comment]
Since all calls to `fetch()` were clearing Collections before, we may try to use `set([...], {reset:true})` for all of those calls and work backwards to what needs it and what doesn't.  Just a hypothesis.

**Comment by davidgtonge** [comment]
I can't see these errors either

**Comment by afeld** [comment]
What's changed since upgrading:

https://github.com/backstopmedia/hubbub/compare/28846614719027f530a802f24dd56d159a116114...backbone-1.0.0
