### ISSUE TITLE
filter state not saving

### ISSUE THREAD

**Issue by davidgtonge** [backstopmedia/hubbub#53]

**Comment by davidgtonge** [comment]
This is caused because the repo model has a default attribute of isActive:true.
As I understand it, the `parse` method on the board is being called each time the repo is saved.
In this method, the repos keep on being updated with the basic data.

**Comment by davidgtonge** [comment]
This issue is a really PITA. I think we may need to adjust the events / saving logic.
I'll look at it in more detail tomorrow. 
I think the synchronous fetching may also be causing some issues - I tried deferring calling `options.success` in the `sync` method until after the current call stack but got stuck in a loop....

**Comment by caseywebdev** [comment]
Fixed by a4ce7da279c488fde93a75475f553165859b2616

Jeremy changed some of the merge logic, but it really makes any model with defaults a bitch to merge correctly =\ Best way to fix this is to not use defaults =p

**Comment by afeld** [comment]
work it y'all :-)
