### ISSUE TITLE
some repos only showing a single issue

### ISSUE THREAD

**Issue by davidgtonge** [backstopmedia/hubbub#55]

**Comment by bluespeckfinancial** [comment]
@caseywebdev, @afeld do you have any more ideas about this bug?
It happens fairly regularly for me. I did an initial check and all the issues have been retrieved and are in the issues collection for each repo. I'll take a more in depth look today.

**Comment by davidgtonge** [comment]
@afeld I can't reproduce this any more after he last commit.
I think we can close this

**Comment by caseywebdev** [comment]
@davidgtonge still happening for me. It's always the first repo in the list. It seems the data is being stored in localStorage, so something is going wrong between the fetch and display (possibly the filtering?).

**Comment by davidgtonge** [comment]
ok, it stated happening for me. The issue models are present in the repo model's issue collection, just not in the boards issue collection

**Comment by davidgtonge** [comment]
@caseywebdev it seems to be something with the update logic.
The issues are being correctly added, but they are then being removed.
The call from our code that causes this to happen is in the `parse` method in the board model:
`_.invoke(_.pluck(this.repos.models, 'issues'), 'fetch');`

Any ideas?
