### ISSUE TITLE
determine basic features

### ISSUE THREAD

**Issue by afeld** [backstopmedia/hubbub#6]
Here's what I'm thinking:
- On first visit, ask for Github username to pull in their repos (see #5)
- Provide a way to view the issues (or at least issue titles) from each of their repos
  - This will be a lot less interesting for new-er programmers with few repos.
- Provide way to organize the issues from the various repos
  - Separate "To Do", "In Progress" and "Done" lists, [Kanban](http://en.wikipedia.org/wiki/Kanban_board)-style?
  - Single long re-orderable list?
  - How do issues get moved around?  Draggable is my first instinct, but that could introduce some complexity with jQuery UI or whatever.
- Minimum issue display:
  - Show issue title, repo name and issue number
  - Link to open it on Github

**Comment by caseywebdev** [comment]
The data layer of the project is pretty much finished. Following the same pattern I've established so far, we can add commits and other GitHub models as we need with little effort.

**Comment by davidgtonge** [comment]
I like the kanban style, but I think we should avoid dragging. We could perhaps rather have a select box or radio inputs for priority of the issues. When the input is changed and the model is saved, the views listening to the model change would update. This would hopefully show new users to Backbone how the views were listening to the model changes. If we are dragging between views it might not be so clear.

I think there should be an option to filter issues - for example by label / priority / assignee / name.

Users without many projects and issues could be given the option of importing issues from an open source project?

**Comment by afeld** [comment]
Maybe it's not so much a matter of pulling in all of _your_ issues, but you type a username/organization and can pick a project to add to the board.

**Comment by caseywebdev** [comment]
I agree, let people use whatever issues they want from any public repo.
